from sqlalchemy import BigInteger, Boolean, Column, Date, DateTime, Float, Integer, Numeric, String, Table, Unicode
# from sqlalchemy.orm import declarative_base
from .masters_models import Base

# Base = declarative_base()
metadata = Base.metadata


t_FactSheet = Table(
    'FactSheet', metadata,
    Column('Plan_Id', BigInteger, nullable=False),
    Column('Plan_Code', Unicode(100)),
    Column('Plan_Name', Unicode(200)),
    Column('Inception_Date', DateTime),
    Column('Fund_Id', BigInteger, nullable=False),
    Column('Fund_Code', Unicode(100)),
    Column('Fund_Name', Unicode(200)),
    Column('Product_Code', Unicode(100)),
    Column('Product_Id', BigInteger, nullable=False),
    Column('Product_Name', Unicode(100)),
    Column('AMC_Id', BigInteger, nullable=False),
    Column('AMC_Code', Unicode(100)),
    Column('AMC_Name', Unicode(100)),
    Column('AMC_Logo', Unicode(500)),
    Column('Classification_Id', BigInteger, nullable=False),
    Column('Classification_Code', Unicode(100)),
    Column('Classification_Name', Unicode(200)),
    Column('BenchmarkIndices_Id', BigInteger, nullable=False),
    Column('BenchmarkIndices_Code', Unicode(100)),
    Column('BenchmarkIndices_Name', Unicode(200)),
    Column('AssetClass_Id', BigInteger, nullable=False),
    Column('AssetClass_Name', Unicode(100)),
    Column('TransactionDate', DateTime),
    Column('FactSheet_Id', BigInteger, nullable=False),
    Column('WeekHigh_52_Rs', Numeric(18, 9)),
    Column('WeekLow_52_Rs', Numeric(18, 9)),
    Column('TotalStocks', Numeric(18, 9)),
    Column('PortfolioP_BRatio', Numeric(18, 9)),
    Column('PortfolioP_ERatio', Numeric(18, 9)),
    Column('EarningsGrowth_3Yrs_Percent', Numeric(18, 9)),
    Column('AvgCreditRating', Numeric(18, 9)),
    Column('ModifiedDuration_yrs', Numeric(18, 9)),
    Column('StandardDeviation', Numeric(18, 9)),
    Column('SharpeRatio', Numeric(18, 9)),
    Column('Beta', Numeric(18, 9)),
    Column('R_Squared', Numeric(18, 9)),
    Column('Alpha', Numeric(18, 9)),
    Column('Mean', Numeric(18, 9)),
    Column('Sortino', Numeric(18, 9)),
    Column('StandardDeviation_1Yr', Numeric(18, 9)),
    Column('SharpeRatio_1Yr', Numeric(18, 9)),
    Column('Beta_1Yr', Numeric(18, 9)),
    Column('R_Squared_1Yr', Numeric(18, 9)),
    Column('Alpha_1Yr', Numeric(18, 9)),
    Column('Mean_1Yr', Numeric(18, 9)),
    Column('Sortino_1Yr', Numeric(18, 9)),
    Column('Equity', Numeric(18, 9)),
    Column('Debt', Numeric(18, 9)),
    Column('Cash', Numeric(18, 9)),
    Column('RANKING_RANK_1MONTH', BigInteger),
    Column('COUNT_1MONTH', BigInteger),
    Column('RANKING_RANK_3MONTH', BigInteger),
    Column('COUNT_3MONTH', BigInteger),
    Column('RANKING_RANK_6MONTH', BigInteger),
    Column('COUNT_6MONTH', BigInteger),
    Column('RANKING_RANK_1YEAR', BigInteger),
    Column('COUNT_1YEAR', BigInteger),
    Column('RANKING_RANK_3YEAR', BigInteger),
    Column('COUNT_3YEAR', BigInteger),
    Column('RANKING_RANK_5YEAR', BigInteger),
    Column('COUNT_5YEAR', BigInteger),
    Column('SIP_RETURNS_1YEAR', Numeric(18, 9)),
    Column('SIP_RETURNS_3YEAR', Numeric(18, 9)),
    Column('SIP_RETURNS_5YEAR', Numeric(18, 9)),
    Column('SIP_RANKINGS_1YEAR', BigInteger),
    Column('SIP_RANKINGS_3YEAR', BigInteger),
    Column('SIP_RANKINGS_5YEAR', BigInteger),
    Column('SCHEME_RETURNS_1MONTH', Numeric(18, 9)),
    Column('SCHEME_RETURNS_3MONTH', Numeric(18, 9)),
    Column('SCHEME_RETURNS_6MONTH', Numeric(18, 9)),
    Column('SCHEME_RETURNS_1YEAR', Numeric(18, 9)),
    Column('SCHEME_RETURNS_3YEAR', Numeric(18, 9)),
    Column('SCHEME_RETURNS_5YEAR', Numeric(18, 9)),
    Column('SCHEME_RETURNS_since_inception', Numeric(18, 9)),
    Column('SCHEME_BENCHMARK_RETURNS_1MONTH', Numeric(18, 9)),
    Column('SCHEME_BENCHMARK_RETURNS_3MONTH', Numeric(18, 9)),
    Column('SCHEME_BENCHMARK_RETURNS_6MONTH', Numeric(18, 9)),
    Column('SCHEME_BENCHMARK_RETURNS_1YEAR', Numeric(18, 9)),
    Column('SCHEME_BENCHMARK_RETURNS_3YEAR', Numeric(18, 9)),
    Column('SCHEME_BENCHMARK_RETURNS_5YEAR', Numeric(18, 9)),
    Column('SCHEME_BENCHMARK_RETURNS_SI', Numeric(18, 9)),
    Column('SCHEME_CATEGORY_AVERAGE_RETURNS_1MONTH', Numeric(18, 9)),
    Column('SCHEME_CATEGORY_AVERAGE_RETURNS_3MONTH', Numeric(18, 9)),
    Column('SCHEME_CATEGORY_AVERAGE_RETURNS_6MONTH', Numeric(18, 9)),
    Column('SCHEME_CATEGORY_AVERAGE_RETURNS_1YEAR', Numeric(18, 9)),
    Column('SCHEME_CATEGORY_AVERAGE_RETURNS_3YEAR', Numeric(18, 9)),
    Column('SCHEME_CATEGORY_AVERAGE_RETURNS_5YEAR', Numeric(18, 9)),
    Column('Risk_Grade', Unicode(100)),
    Column('Return_Grade', Unicode(100)),
    Column('Exit_Load', Unicode(500)),
    Column('ExpenseRatio', Numeric(18, 9)),
    Column('SOV', Numeric(18, 9)),
    Column('AAA', Numeric(18, 9)),
    Column('A1_Plus', Numeric(18, 9)),
    Column('AA', Numeric(18, 9)),
    Column('A_and_Below', Numeric(18, 9)),
    Column('Bill_Rediscounting', Numeric(18, 9)),
    Column('Cash_Equivalent', Numeric(18, 9)),
    Column('Term_Deposit', Numeric(18, 9)),
    Column('Unrated_Others', Numeric(18, 9)),
    Column('Bonds_Debentures', Numeric(18, 9)),
    Column('Cash_And_Cash_Equivalent', Numeric(18, 9)),
    Column('CP_CD', Numeric(18, 9)),
    Column('GOI_Securities', Numeric(18, 9)),
    Column('MutualFunds_Debt', Numeric(18, 9)),
    Column('Securitised_Debt', Numeric(18, 9)),
    Column('ShortTerm_Debt', Numeric(18, 9)),
    Column('Term_Deposits', Numeric(18, 9)),
    Column('Treasury_Bills', Numeric(18, 9)),
    Column('VRRatings', BigInteger),
    Column('NetAssets_Rs_Cr', Numeric(18, 9)),
    Column('AvgMktCap_Rs_Cr', Numeric(18, 9)),
    Column('AvgMaturity_Yrs', Numeric(18, 9)),
    Column('SourceFlag', Unicode(20)),
    Column('Portfolio_Dividend_Yield', Numeric(18, 9)),
    Column('Churning_Ratio', Numeric(18, 9)),
    Column('Portfolio_Sales_Growth_Estimated', Numeric(18, 9)),
    Column('Portfolio_PAT_Growth_Estimated', Numeric(18, 9)),
    Column('Portfolio_Earning_Growth_Estimated', Numeric(18, 9)),
    Column('Portfolio_Forward_PE', Numeric(18, 9)),
    Column('Created_By', BigInteger),
    Column('Created_Date', DateTime),
    Column('Updated_By', BigInteger),
    Column('Updated_Date', DateTime),
    schema='Logics'
)


t_FactSheet_Latest = Table(
    'FactSheet_Latest', metadata,
    Column('Plan_Id', BigInteger, nullable=False),
    Column('Plan_Code', Unicode(100)),
    Column('Plan_Name', Unicode(200)),
    Column('Inception_Date', DateTime),
    Column('Fund_Id', BigInteger, nullable=False),
    Column('Fund_Code', Unicode(100)),
    Column('Fund_Name', Unicode(200)),
    Column('Product_Code', Unicode(100)),
    Column('Product_Id', BigInteger, nullable=False),
    Column('Product_Name', Unicode(100)),
    Column('AMC_Id', BigInteger, nullable=False),
    Column('AMC_Code', Unicode(100)),
    Column('AMC_Name', Unicode(100)),
    Column('AMC_Logo', Unicode(500)),
    Column('Classification_Id', BigInteger, nullable=False),
    Column('Classification_Code', Unicode(100)),
    Column('Classification_Name', Unicode(200)),
    Column('BenchmarkIndices_Id', BigInteger, nullable=False),
    Column('BenchmarkIndices_Code', Unicode(100)),
    Column('BenchmarkIndices_Name', Unicode(200)),
    Column('AssetClass_Id', BigInteger, nullable=False),
    Column('AssetClass_Name', Unicode(100)),
    Column('TransactionDate', DateTime),
    Column('FactSheet_Id', BigInteger, nullable=False),
    Column('WeekHigh_52_Rs', Numeric(18, 9)),
    Column('WeekLow_52_Rs', Numeric(18, 9)),
    Column('TotalStocks', Numeric(18, 9)),
    Column('PortfolioP_BRatio', Numeric(18, 9)),
    Column('PortfolioP_ERatio', Numeric(18, 9)),
    Column('EarningsGrowth_3Yrs_Percent', Numeric(18, 9)),
    Column('AvgCreditRating', Numeric(18, 9)),
    Column('ModifiedDuration_yrs', Numeric(18, 9)),
    Column('StandardDeviation', Numeric(18, 9)),
    Column('SharpeRatio', Numeric(18, 9)),
    Column('Beta', Numeric(18, 9)),
    Column('R_Squared', Numeric(18, 9)),
    Column('Alpha', Numeric(18, 9)),
    Column('Mean', Numeric(18, 9)),
    Column('Sortino', Numeric(18, 9)),
    Column('StandardDeviation_1Yr', Numeric(18, 9)),
    Column('SharpeRatio_1Yr', Numeric(18, 9)),
    Column('Beta_1Yr', Numeric(18, 9)),
    Column('R_Squared_1Yr', Numeric(18, 9)),
    Column('Alpha_1Yr', Numeric(18, 9)),
    Column('Mean_1Yr', Numeric(18, 9)),
    Column('Sortino_1Yr', Numeric(18, 9)),
    Column('Equity', Numeric(18, 9)),
    Column('Debt', Numeric(18, 9)),
    Column('Cash', Numeric(18, 9)),
    Column('RANKING_RANK_1MONTH', BigInteger),
    Column('COUNT_1MONTH', BigInteger),
    Column('RANKING_RANK_3MONTH', BigInteger),
    Column('COUNT_3MONTH', BigInteger),
    Column('RANKING_RANK_6MONTH', BigInteger),
    Column('COUNT_6MONTH', BigInteger),
    Column('RANKING_RANK_1YEAR', BigInteger),
    Column('COUNT_1YEAR', BigInteger),
    Column('RANKING_RANK_3YEAR', BigInteger),
    Column('COUNT_3YEAR', BigInteger),
    Column('RANKING_RANK_5YEAR', BigInteger),
    Column('COUNT_5YEAR', BigInteger),
    Column('SIP_RETURNS_1YEAR', Numeric(18, 9)),
    Column('SIP_RETURNS_3YEAR', Numeric(18, 9)),
    Column('SIP_RETURNS_5YEAR', Numeric(18, 9)),
    Column('SIP_RANKINGS_1YEAR', BigInteger),
    Column('SIP_RANKINGS_3YEAR', BigInteger),
    Column('SIP_RANKINGS_5YEAR', BigInteger),
    Column('SCHEME_RETURNS_1MONTH', Numeric(18, 9)),
    Column('SCHEME_RETURNS_3MONTH', Numeric(18, 9)),
    Column('SCHEME_RETURNS_6MONTH', Numeric(18, 9)),
    Column('SCHEME_RETURNS_1YEAR', Numeric(18, 9)),
    Column('SCHEME_RETURNS_3YEAR', Numeric(18, 9)),
    Column('SCHEME_RETURNS_5YEAR', Numeric(18, 9)),
    Column('SCHEME_RETURNS_since_inception', Numeric(18, 9)),
    Column('SCHEME_BENCHMARK_RETURNS_1MONTH', Numeric(18, 9)),
    Column('SCHEME_BENCHMARK_RETURNS_3MONTH', Numeric(18, 9)),
    Column('SCHEME_BENCHMARK_RETURNS_6MONTH', Numeric(18, 9)),
    Column('SCHEME_BENCHMARK_RETURNS_1YEAR', Numeric(18, 9)),
    Column('SCHEME_BENCHMARK_RETURNS_3YEAR', Numeric(18, 9)),
    Column('SCHEME_BENCHMARK_RETURNS_5YEAR', Numeric(18, 9)),
    Column('SCHEME_BENCHMARK_RETURNS_SI', Numeric(18, 9)),
    Column('SCHEME_CATEGORY_AVERAGE_RETURNS_1MONTH', Numeric(18, 9)),
    Column('SCHEME_CATEGORY_AVERAGE_RETURNS_3MONTH', Numeric(18, 9)),
    Column('SCHEME_CATEGORY_AVERAGE_RETURNS_6MONTH', Numeric(18, 9)),
    Column('SCHEME_CATEGORY_AVERAGE_RETURNS_1YEAR', Numeric(18, 9)),
    Column('SCHEME_CATEGORY_AVERAGE_RETURNS_3YEAR', Numeric(18, 9)),
    Column('SCHEME_CATEGORY_AVERAGE_RETURNS_5YEAR', Numeric(18, 9)),
    Column('Risk_Grade', Unicode(100)),
    Column('Return_Grade', Unicode(100)),
    Column('Exit_Load', Unicode(500)),
    Column('ExpenseRatio', Numeric(18, 9)),
    Column('SOV', Numeric(18, 9)),
    Column('AAA', Numeric(18, 9)),
    Column('A1_Plus', Numeric(18, 9)),
    Column('AA', Numeric(18, 9)),
    Column('A_and_Below', Numeric(18, 9)),
    Column('Bill_Rediscounting', Numeric(18, 9)),
    Column('Cash_Equivalent', Numeric(18, 9)),
    Column('Term_Deposit', Numeric(18, 9)),
    Column('Unrated_Others', Numeric(18, 9)),
    Column('Bonds_Debentures', Numeric(18, 9)),
    Column('Cash_And_Cash_Equivalent', Numeric(18, 9)),
    Column('CP_CD', Numeric(18, 9)),
    Column('GOI_Securities', Numeric(18, 9)),
    Column('MutualFunds_Debt', Numeric(18, 9)),
    Column('Securitised_Debt', Numeric(18, 9)),
    Column('ShortTerm_Debt', Numeric(18, 9)),
    Column('Term_Deposits', Numeric(18, 9)),
    Column('Treasury_Bills', Numeric(18, 9)),
    Column('VRRatings', BigInteger),
    Column('NetAssets_Rs_Cr', Numeric(18, 9)),
    Column('AvgMktCap_Rs_Cr', Numeric(18, 9)),
    Column('AvgMaturity_Yrs', Numeric(18, 9)),
    Column('SourceFlag', Unicode(20)),
    Column('Portfolio_Dividend_Yield', Numeric(18, 9)),
    Column('Churning_Ratio', Numeric(18, 9)),
    Column('Portfolio_Sales_Growth_Estimated', Numeric(18, 9)),
    Column('Portfolio_PAT_Growth_Estimated', Numeric(18, 9)),
    Column('Portfolio_Earning_Growth_Estimated', Numeric(18, 9)),
    Column('Portfolio_Forward_PE', Numeric(18, 9)),
    Column('Created_By', BigInteger),
    Column('Created_Date', DateTime),
    Column('Updated_By', BigInteger),
    Column('Updated_Date', DateTime),
    schema='Logics'
)


t_Fund_Constituents = Table(
    'Fund_Constituents', metadata,
    Column('Plan_Id', BigInteger, nullable=False),
    Column('Plan_Code', Unicode(100)),
    Column('Plan_Name', Unicode(200)),
    Column('Date', DateTime),
    Column('ISIN', Unicode(200)),
    Column('Weight_in_Percentage', Numeric(30, 9)),
    schema='Logics'
)


t_Fund_NAV = Table(
    'Fund_NAV', metadata,
    Column('Plan_Id', BigInteger, nullable=False),
    Column('Plan_Code', Unicode(100)),
    Column('Plan_Name', Unicode(200)),
    Column('NAV_Date', Date),
    Column('NAV', Float(53)),
    schema='Logics'
)


t_Index_Constituents = Table(
    'Index_Constituents', metadata,
    Column('BenchmarkIndices_Id', BigInteger, nullable=False),
    Column('BenchmarkIndices_Name', Unicode(200)),
    Column('Date', DateTime),
    Column('ISIN', Unicode(50)),
    Column('Weight_in_Percentage', Float(53)),
    schema='Logics'
)


t_Index_NAV = Table(
    'Index_NAV', metadata,
    Column('BenchmarkIndices_Id', BigInteger, nullable=False),
    Column('BenchmarkIndices_Code', Unicode(100)),
    Column('BenchmarkIndices_Name', Unicode(200)),
    Column('NAV_Date', Date),
    Column('NAV', Float(53)),
    schema='Logics'
)


t_Plans = Table(
    'Plans', metadata,
    Column('Plan_Id', BigInteger, nullable=False),
    Column('Plan_Code', Unicode(100)),
    Column('Plan_Name', Unicode(200)),
    Column('Inception_Date', DateTime),
    Column('Fund_Id', BigInteger, nullable=False),
    Column('Fund_Code', Unicode(100)),
    Column('Fund_Name', Unicode(200)),
    Column('AutoPopulate', Boolean, nullable=False),
    Column('HideHoldingWeightage', Boolean, nullable=False),
    Column('Top_Holding_ToBeShown', Integer),
    Column('HideAttribution', Boolean, nullable=False),
    Column('HidePortfolioHoldingChanges', Boolean, nullable=False),
    Column('Product_Code', Unicode(100)),
    Column('Product_Id', BigInteger, nullable=False),
    Column('Product_Name', Unicode(100)),
    Column('AMC_Id', BigInteger, nullable=False),
    Column('AMC_Code', Unicode(100)),
    Column('AMC_Name', Unicode(100)),
    Column('AMC_Logo', Unicode(500)),
    Column('Classification_Id', BigInteger, nullable=False),
    Column('Classification_Code', Unicode(100)),
    Column('Classification_Name', Unicode(200)),
    Column('BenchmarkIndices_Id', BigInteger, nullable=False),
    Column('BenchmarkIndices_Code', Unicode(100)),
    Column('BenchmarkIndices_Name', Unicode(200)),
    Column('AssetClass_Id', BigInteger, nullable=False),
    Column('AssetClass_Name', Unicode(100)),
    Column('PlanType_Id', BigInteger),
    Column('MF_Security_OpenDate', DateTime),
    schema='Logics'
)


t_Scrip_Master = Table(
    'Scrip_Master', metadata,
    Column('ISIN_Code', Unicode(50)),
    Column('Symbol', Unicode(50)),
    Column('Name', Unicode(500)),
    Column('Sector', Unicode(200)),
    Column('Capitalization', Integer),
    Column('Asset_Class', String(6, 'SQL_Latin1_General_CP1_CI_AS'), nullable=False),
    schema='Logics'
)


t_Security_NAV = Table(
    'Security_NAV', metadata,
    Column('ISIN_Code', Unicode(50)),
    Column('Date', DateTime),
    Column('CLOSE', Float(53)),
    schema='Logics'
)


t_UnderlyingHoldings = Table(
    'UnderlyingHoldings', metadata,
    Column('Underlying_Holdings_Id', BigInteger, nullable=False),
    Column('AMC_Id', BigInteger, nullable=False),
    Column('AMC_Name', Unicode(100)),
    Column('Plan_Id', BigInteger, nullable=False),
    Column('Plan_Code', Unicode(100)),
    Column('Plan_Name', Unicode(200)),
    Column('BenchmarkIndices_Id', BigInteger),
    Column('BenchmarkIndices_Code', Unicode(100)),
    Column('BenchmarkIndices_Name', Unicode(200)),
    Column('AssetClass_Id', BigInteger, nullable=False),
    Column('AssetClass_Name', Unicode(100)),
    Column('MF_Security_OpenDate', DateTime),
    Column('Product_Code', Unicode(100)),
    Column('Product_Id', BigInteger, nullable=False),
    Column('Product_Name', Unicode(100)),
    Column('Fund_Id', BigInteger, nullable=False),
    Column('Fund_Code', Unicode(100)),
    Column('Fund_Name', Unicode(200)),
    Column('ISIN_Code', Unicode(200)),
    Column('Portfolio_Date', DateTime),
    Column('Asset_Class', Unicode(100)),
    Column('Percentage_to_AUM', Numeric(18, 2)),
    Column('Value_in_INR', Numeric(25, 10)),
    Column('Risk_Category', Unicode(100), nullable=False),
    Column('InstrumentType', Unicode(100)),
    Column('MarketCap', Numeric(25, 10)),
    Column('StocksRank', Unicode(50), nullable=False),
    Column('HoldingSecurity_Id', BigInteger),
    Column('HoldingSecurity_Name', Unicode(500)),
    Column('Equity_Style', Unicode(20), nullable=False),
    Column('Sector_Code', Unicode(100)),
    Column('Sector_Name', Unicode(300)),
    Column('Sector_Id', BigInteger),
    Column('Issuer_Code', Unicode(100)),
    Column('Issuer_Name', Unicode(200)),
    Column('Issuer_Id', BigInteger),
    Column('HoldingSecurity_Type', Unicode(50)),
    Column('Co_Code', BigInteger),
    Column('LISTED_UNLISTED', String(50, 'SQL_Latin1_General_CP1_CI_AS'), nullable=False),
    schema='Logics'
)
